services:
  postgres:
    container_name: purch-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - purch

  redis:
    container_name: purch-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    networks:
      - purch

  purch:
    build:
      context: .
      dockerfile: docker/dockerfile.purch
    command: /app/.venv/bin/fastapi dev purch/main.py --host 0.0.0.0 --port 8080
    volumes:
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - purch

  taskiq-worker:
    build:
      context: .
      dockerfile: docker/dockerfile.purch
    command: /app/.venv/bin/taskiq worker purch.core:broker
    volumes:
      - ./.env:/app/.env
    depends_on:
      redis:
        condition: service_healthy 
    restart: unless-stopped
    networks:
      - purch

  taskiq-scheduler:
    build:
      context: .
      dockerfile: docker/dockerfile.purch
    command: /app/.venv/bin/taskiq scheduler purch.core:scheduler
    volumes:
      - ./.env:/app/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - purch

  
networks:
  purch:

volumes:
  postgres_data:
  redis_data:
